# 首页引用语
quote:
  text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away."
  author: "Antoine de Saint-Exupéry"

# 社交链接
social:
  GitHub: "https://github.com/FengIKUN"
  Twitter: "https://twitter.com/fengikunmu"
  Mail: "mailto:feng.ikunmu@foxmail.com"